import { useEffect, useMemo, useState } from "react";
import {
  FaAward,
  FaBookOpen,
  FaChartLine,
  FaCheckCircle,
  FaClock,
  FaHistory,
  FaFilePdf,
} from "react-icons/fa";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Layout from "../components/Layout";
import api from "../api";

const courseIdOf = (course) => String(course?._id || course || "");

function MyResults() {
  const [courses, setCourses] = useState([]);
  const [assessments, setAssessments] = useState([]);
  const [selectedCourse, setSelectedCourse] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let active = true;

    const loadData = async () => {
      try {
        setLoading(true);
        setError("");
        const { data } = await api.get("/assessment/my-results");
        if (!active) return;

        const nextCourses = Array.isArray(data?.courses) ? data.courses : [];
        const nextAssessments = Array.isArray(data?.assessments) ? data.assessments : [];
        setCourses(nextCourses);
        setAssessments(nextAssessments);

        if (nextCourses.length) {
          setSelectedCourse((current) => {
            if (current && nextCourses.some((course) => courseIdOf(course) === current)) {
              return current;
            }
            return courseIdOf(nextCourses[0]);
          });
        } else {
          setSelectedCourse("");
        }
      } catch (err) {
        if (active) {
          setError(err.response?.data?.message || "Unable to load your results.");
        }
      } finally {
        if (active) setLoading(false);
      }
    };

    loadData();
    return () => {
      active = false;
    };
  }, []);

  const courseResults = useMemo(
    () =>
      assessments.filter(
        (assessment) => courseIdOf(assessment.course) === String(selectedCourse)
      ),
    [assessments, selectedCourse]
  );

  const rows = useMemo(
    () =>
      courseResults.map((assessment) => {
        const entered = assessment?.result?.entered === true;
        const score = Number(assessment?.result?.score || 0);
        const total = Number(assessment?.totalMark || 100);
        const percentage = entered && total ? Math.round((score / total) * 100) : null;
        return { assessment, entered, score, total, percentage };
      }),
    [courseResults]
  );

  const publishedRows = rows.filter((row) => row.entered);
  const completed = publishedRows.length;
  const average = completed
    ? Math.round(
        publishedRows.reduce((sum, row) => sum + Number(row.percentage || 0), 0) /
          completed
      )
    : 0;
  const passed = publishedRows.filter((row) => Number(row.percentage) >= 50).length;
  const pending = rows.length - completed;

  const selectedCourseInfo = courses.find(
    (course) => courseIdOf(course) === String(selectedCourse)
  );

  const exportReport = () => {
    if (!selectedCourseInfo) return;
    const doc = new jsPDF();
    const navy = [15, 43, 91];
    doc.setFillColor(...navy);
    doc.rect(0, 0, 210, 34, "F");
    doc.setTextColor(255,255,255);
    doc.setFont("helvetica","bold");
    doc.setFontSize(18);
    doc.text("AeroLearn Academic Report", 14, 15);
    doc.setFontSize(9);
    doc.setFont("helvetica","normal");
    doc.text(`${selectedCourseInfo.code || ""} • ${selectedCourseInfo.name || "Course"}`, 14, 23);
    doc.text(`${selectedCourseInfo.studyYear || ""} • ${selectedCourseInfo.semester || ""}`, 14, 29);
    doc.setTextColor(30,41,59);
    doc.setFontSize(10);
    doc.text(`Published: ${completed}     Passed: ${passed}     Pending: ${pending}     Average: ${average}%`, 14, 44);
    autoTable(doc, {
      startY: 51,
      head: [["Assessment","Category","Score","Weight","Status","Performance"]],
      body: rows.map(({assessment,entered,score,total,percentage}) => [
        assessment.title || assessment.category || "Assessment",
        assessment.category || "Assessment",
        entered ? `${score} / ${total}` : `— / ${total}`,
        `${assessment.weight || 0}%`,
        entered ? "Published" : "Pending",
        entered ? `${percentage}%` : "Waiting",
      ]),
      theme: "grid",
      headStyles: { fillColor: navy, textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 8.5, cellPadding: 3 },
      alternateRowStyles: { fillColor: [248,250,252] },
    });
    const y = (doc.lastAutoTable?.finalY || 60) + 12;
    doc.setFontSize(8);
    doc.setTextColor(100,116,139);
    doc.text(`Generated by AeroLearn • ${new Date().toLocaleString()}`, 14, Math.min(y, 286));
    const file = `${selectedCourseInfo.code || "course"}_academic_report.pdf`.replace(/[^a-zA-Z0-9._-]+/g,"_");
    doc.save(file);
  };

  return (
    <Layout>
      <div className="student-results-page">
        <header className="student-page-banner compact-banner result-hero">
          <div>
            <span className="student-eyebrow"><FaChartLine /> Academic performance</span>
            <h1>My Results</h1>
            <p>Your current and previous course results stay available in one place.</p>
          </div>
          <div className="result-hero-actions">
            {selectedCourseInfo && <button type="button" className="result-export-btn" onClick={exportReport}><FaFilePdf /> Download report</button>}
            <div className="student-banner-mark"><FaAward /></div>
          </div>
        </header>

        {error && <div className="student-alert error">{error}</div>}

        <div className="student-result-stats">
          <div><span className="metric-icon blue"><FaBookOpen /></span><strong>{courses.length}</strong><small>Courses</small></div>
          <div><span className="metric-icon violet"><FaCheckCircle /></span><strong>{completed}</strong><small>Published</small></div>
          <div><span className="metric-icon green"><FaAward /></span><strong>{passed}</strong><small>Passed</small></div>
          <div><span className="metric-icon amber"><FaChartLine /></span><strong>{average}%</strong><small>Average</small></div>
        </div>

        <div className="student-filter-strip result-filter-strip">
          <div className="result-course-picker">
            <label>Course</label>
            <select value={selectedCourse} onChange={(e) => setSelectedCourse(e.target.value)}>
              <option value="">Select course</option>
              {courses.map((course) => (
                <option key={course._id} value={course._id}>
                  {course.code} — {course.name}
                </option>
              ))}
            </select>
          </div>
          <div className="result-filter-meta">
            {selectedCourseInfo && (
              <span>{selectedCourseInfo.studyYear || ""} · {selectedCourseInfo.semester || ""}</span>
            )}
            <span>{completed} published</span>
            {pending > 0 && <span className="result-pending-chip"><FaClock /> {pending} pending</span>}
          </div>
        </div>

        {loading ? (
          <div className="student-empty-state">Loading your academic record…</div>
        ) : !selectedCourse ? (
          <div className="student-empty-state">
            <FaHistory />
            <strong>No course results available yet</strong>
            <span>Your results will appear here as soon as a course and assessment are available.</span>
          </div>
        ) : (
          <div className="al-table-shell student-results-table">
            <table className="al-table al-table-blue">
              <thead>
                <tr>
                  <th>Assessment</th>
                  <th>Category</th>
                  <th>Score</th>
                  <th>Weight</th>
                  <th>Status</th>
                  <th>Performance</th>
                </tr>
              </thead>
              <tbody>
                {rows.length === 0 ? (
                  <tr><td colSpan="6" className="al-empty-cell">No assessments have been created for this course yet.</td></tr>
                ) : rows.map(({ assessment, entered, score, total, percentage }) => (
                  <tr key={assessment._id}>
                    <td className="al-strong-cell">
                      <div>{assessment.title || assessment.category}</div>
                      <small>Week {assessment.week || "—"}</small>
                    </td>
                    <td><span className="student-category-pill">{assessment.category || "Assessment"}</span></td>
                    <td>{entered ? <><strong>{score}</strong> / {total}</> : <span className="result-muted">— / {total}</span>}</td>
                    <td>{assessment.weight || 0}%</td>
                    <td>
                      <span className={`result-status ${entered ? "published" : "pending"}`}>
                        {entered ? "Published" : "Pending"}
                      </span>
                    </td>
                    <td>
                      {entered ? (
                        <span className={`student-performance ${percentage >= 80 ? "excellent" : percentage >= 50 ? "pass" : "risk"}`}>
                          {percentage}%
                        </span>
                      ) : (
                        <span className="result-muted">Waiting for score</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </Layout>
  );
}

export default MyResults;
