import { useEffect, useMemo, useState } from "react";
import { FaChartBar, FaCheckCircle, FaTimesCircle } from "react-icons/fa";
import Layout from "../components/Layout";
import api from "../api";
import "../styles/workspace.css";

function ViewResults(){
 const departments=["Aerospace Engineering","Armament Engineering","Computer Engineering","Software Engineering","Information Technology","Computer Science","Electrical Engineering","Mechanical Engineering","Civil Engineering","Chemical Engineering"];
 const [courses,setCourses]=useState([]),[assessments,setAssessments]=useState([]),[department,setDepartment]=useState(""),[course,setCourse]=useState(""),[assessment,setAssessment]=useState(""),[selected,setSelected]=useState(null),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const [c,a]=await Promise.all([api.get("/courses"),api.get("/assessment")]);setCourses(Array.isArray(c.data.courses)?c.data.courses:Array.isArray(c.data)?c.data:[]);setAssessments(Array.isArray(a.data)?a.data:[]);}catch(err){setError(err.response?.data?.message||"Unable to load results.");}})();},[]);
 useEffect(()=>{if(!assessment){setSelected(null);return;} (async()=>{try{const r=await api.get(`/assessment/${assessment}`);setSelected(r.data);}catch(err){setError(err.response?.data?.message||"Unable to load assessment results.");}})();},[assessment]);
 const filteredCourses=useMemo(()=>courses.filter(c=>c.department===department),[courses,department]); const filteredAssessments=useMemo(()=>assessments.filter(a=>a.course&&(typeof a.course==="object"?a.course._id===course:a.course===course)),[assessments,course]);
 const rows=selected?.scores||[]; const passed=rows.filter(x=>((Number(x.score)||0)/(Number(selected?.totalMark)||1))*100>=50).length; const avg=rows.length?rows.reduce((s,x)=>s+(Number(x.score)||0),0)/rows.length:0; const avgPct=selected?.totalMark?avg/selected.totalMark*100:0;
 return <Layout><div className="workspace-page"><nav className="ops-flow assessment-flow" aria-label="Academic operations"><span><b>1</b> Attendance</span><span><b>2</b> Assessment</span><span><b>3</b> Scores</span><span className="active"><b>4</b> Results</span><span><b>5</b> Resources</span></nav><section className="workspace-head"><div><h1><FaChartBar/> Assessment Results</h1><p>Review class performance with a compact score and pass/fail summary.</p></div><div className="head-badge"><strong>{rows.length}</strong><span>Results</span></div></section>{error&&<div className="message-strip error">{error}</div>}
 <section className="workspace-card"><div className="workspace-card-head"><div><h2>Result filters</h2><p>Choose the exact assessment you want to review</p></div></div><div className="workspace-card-body compact-filter-grid"><div className="field"><label>Department</label><select value={department} onChange={e=>{setDepartment(e.target.value);setCourse("");setAssessment("");}}><option value="">Select department</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div><div className="field"><label>Course</label><select value={course} disabled={!department} onChange={e=>{setCourse(e.target.value);setAssessment("");}}><option value="">Select course</option>{filteredCourses.map(c=><option key={c._id} value={c._id}>{c.code} — {c.name}</option>)}</select></div><div className="field"><label>Assessment</label><select value={assessment} disabled={!course} onChange={e=>setAssessment(e.target.value)}><option value="">Select assessment</option>{filteredAssessments.map(a=><option key={a._id} value={a._id}>{a.title||a.category}</option>)}</select></div></div></section>
 <div className="mini-stats"><div className="mini-stat" style={{"--tone":"#2563eb"}}><div className="dot"/><div><strong>{rows.length}</strong><span>Students</span></div></div><div className="mini-stat" style={{"--tone":"#10b981"}}><div className="dot"/><div><strong>{passed}</strong><span>Passed</span></div></div><div className="mini-stat" style={{"--tone":"#ef4444"}}><div className="dot"/><div><strong>{Math.max(rows.length-passed,0)}</strong><span>Failed</span></div></div><div className="mini-stat" style={{"--tone":"#7c3aed"}}><div className="dot"/><div><strong>{avgPct.toFixed(1)}%</strong><span>Class average</span></div></div></div>
 <section className="workspace-card"><div className="workspace-card-head"><div><h2>{selected?.title||selected?.category||"Score register"}</h2><p>{selected?`Total mark ${selected.totalMark} · ${selected.category}`:"Select an assessment to view scores"}</p></div>{selected&&<div className="score-summary"><span className="pill pill-blue">{selected.weight}% weight</span></div>}</div>{!selected?<div className="empty-state"><strong>No assessment selected</strong>Use the filters above to open a result sheet.</div>:rows.length===0?<div className="empty-state"><strong>No scores submitted</strong>This assessment does not have saved scores yet.</div>:<div className="data-wrap"><table className="data-table"><thead><tr><th>#</th><th>Student ID</th><th>Student name</th><th>Score</th><th>Total</th><th>Percentage</th><th>Result</th></tr></thead><tbody>{rows.map((x,i)=>{const pct=((Number(x.score)||0)/(Number(selected.totalMark)||1))*100;return <tr key={x.student?._id||i}><td>{i+1}</td><td><span className="table-id">{x.student?.studentId||"—"}</span></td><td><strong>{x.student?.fullName||"Unknown student"}</strong></td><td><strong>{x.score}</strong></td><td>{selected.totalMark}</td><td>{pct.toFixed(1)}%</td><td>{pct>=50?<span className="pill pill-green"><FaCheckCircle/> Pass</span>:<span className="pill pill-red"><FaTimesCircle/> Fail</span>}</td></tr>})}</tbody></table></div>}</section></div></Layout>;
}
export default ViewResults;
